services:
  m0001-info:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: "m0001-info"

    restart: always

    ports:
      - "3180:80"

    networks:
      - reverse_proxy 

networks:
  reverse_proxy:
    name: "n0000-reverse_proxy"
    external: true
