services:
  m0000-blog:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: "m0001-info"

    restart: always

    ports:
      - "5173:80"

    volumes:

    networks:
      - reverse_proxy 

networks:
  reverse_proxy:
    name: "n0000-reverse_proxy"
    external: true
